name: leakpro
channels:
  - conda-forge
dependencies:
  # Core Python
  - python=3.9.0 

  # Numerical and Data Analysis
  - numpy  
  - pandas  
  - scipy
  - scikit-learn

  # Visualization
  - matplotlib  
  - seaborn
  - pillow

  # Deep Learning
  - pytorch
  - torchvision

  # Utilities
  - dotmap
  - loguru
  - jinja2
  - tqdm
  - pyyaml
  - tqdm

  # Development and Testing
  - pytest
  

