run: # Configurations for a specific run
  random_seed: 1236 # Integer number of specifying random seed
  log_dir: ./target # String for indicating where to save all the information, including models and computed signals. We can reuse the models saved in the same log_dir.

train:


data: # Configuration for data
  dataset: pubmed_central # String indicates the name of the dataset [arxiv, dm_mathematics, github, hackernews, pile_cc, pubmed_central]
  f_train: 0.5 # Float number from 0 to 1 indicating the fraction of the train dataset
  f_test: 0.5 # Float number from 0 to 1 indicating the size of the test set
  data_dir: ./data # String about where to save the data.